version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "sample"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./mysql:/etc/mysql/conf.d"
      - "./mysql/data:/var/lib/mysql"
      - "./mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
  app:
    image: golang:1.9
    command: "go run main.go"
    volumes:
      - ./server:/go/src/github.com/SekiguchiKai/clean-architecture-with-go/server
    working_dir: /go/src/github.com/SekiguchiKai/clean-architecture-with-go/server
    ports:
      - "8080:8080"
    depends_on:
      - db
